 App.Genres = [
 	'comedy',
 	'drama',
 	'horror',
 	'kids',
 	'mystery',
 	'paranormal teen romance',
 	'police procedural',
 	'romance',
 	'romantic comedy',
 	'sci-fi',
 	'sports',
 	'suspense',
 	'western',
 ];