App.Worlds = Em.A([
	Ember.Object.create({
		name: "Naruto",
		google: 76000000,
		popularity: 70,
		weirdness: 0.01,
		genre: ['action', 'adventure'],
		medium: 'manga',
		characters: ['Naruto', 'Sasuke', 'Sakura', 'Hinata', 'Kakashi', 'Orochimaru', 'Gaara'],
		locations: ['Konoha', 'Hidden Sand Village', 'Country of Stone', 'Ninja Academy'],
		props: ['Shadow Clone Jutstu', 'Rasengan', 'Icha Icha Paradice'],
		fuckingWat: false
	}), Ember.Object.create({
		name: "Star Wars",
		google: 72000000,
		popularity: 95,
		weirdness: 0.02,
		genre: ['sci-fi', 'adventure'],
		medium: 'movie',
		characters: ['Han Solo', 'Luke Skywalker', 'Chewbacka', 'General Grievous', 'Mace Windu', 'Princess Leah', 'Princess Amidala', 'Darth Vader'],
		locations: ['Tatooine', 'Hoth', 'Endor', 'Death Star'],
		props: ['lightsabre', 'X-Wing', 'midichlorians', 'Sarlacc', 'the Force'],
		fuckingWat: false
	}), Ember.Object.create({
		name: "Star Trek: The Next Generation",
		popularity: 35,
		google: 16400000,
		weirdness: 0.03,
		genre: ['sci-fi'],
		medium: 'TV',
		characters: ['Worf', 'Data', 'Jean Luc Picard', 'Wesley Crusher', 'Q', 'Counselor Troi', 'Dr. Crusher', 'Lwaxana Troi', 'Guinan'],
		locations: ['Star Fleet Academy', 'Wolf 359', 'Betazed', 'Delta Quadrent', 'The Q Continuum', "Qo'noS"],
		props: ['tricorder', 'phaser', 'cloaking device', 'dilithium crystal', 'Borg technology', 'the Sacred Chalice of Rixx'],
		fuckingWat: false
	}), Ember.Object.create({
		name: "Muppet Babies",
		google: 762000,
		popularity: 20,
		weirdness: 0.8,
		genre: ['comedy', 'kids'],
		medium: 'cartoon',
		characters: ['Nanny', 'Baby Fozzie Bear', 'Baby Piggy', 'Baby Gonzo', 'Baby Rowlf'],
		locations: ['the nursery', 'Doorknob World'],
		props: ['imagination', 'old toys', "Nanny's socks"],
		fuckingWat: true
	}), Ember.Object.create({
		name: "The Wonder Years",
		google: 747000,
		popularity: 20,
		weirdness: 0.75,
		genre: ['drama'],
		medium: 'TV',
		characters: ['Kevin Arnold', 'Winnie Cooper', 'Paul Joshua Pfeiffer', 'Wayne Arnold'],
		locations: ["Winnie's beddroom", "Lincoln Junior High", "McKinley High School", "NORCOM"],
		props: ['first car', 'first kiss', 'first fight'],
		fuckingWat: true
	}), Ember.Object.create({
		name: "Doctor Who",
		google: 31700000,
		popularity: 60,
		weirdness: 0.01,
		genre: ['sci-fi', 'adventure'],
		medium: 'tv',
		characters: ['The Doctor', 'Strax', 'River Song', 'The Master', 'Davros', 'Clara', 'Rory Willimas'],
		locations: ['Earth', 'TARDIS', 'Gallifrey', 'E-Space', 'Mondas'],
		props: ['sonic screw driver', 'TARDIS', 'Dalekanium', 'psychic paper', 'timey-wimey stuff'],
		fuckingWat: false
	}), Ember.Object.create({
		name: "Winnie-the-Pooh",
		google: 9810000,
		popularity: 20,
		weirdness: 0.68,
		genre: ['comedy', 'kids'],
		medium: 'book',
		characters: ['Winnie-the-Pooh', 'Piglet', 'Tigger', 'Christopher Robin', 'Eeyore', 'Hephalumps'],
		locations: ["The Hundred Acre Wood", "Six Pine Trees", "Where The Woozle Wasn't", "Pooh Corner", "Owl's House"],
		props: ['honey', 'Pooh Sticks', 'the North Pole', "Hephalumps"],
		fuckingWat: true
	}),
	Ember.Object.create({
		name: "Harry Potter",
		google: 9810000,
		popularity: 70,
		weirdness: 0.02,
		genre: ['comedy', 'kids', 'adnedture', 'fantasy', ],
		medium: 'book',
		characters: ['Harry Potter', 'Hagrid', 'Snape', 'Dobby', 'Petunia Dursley', 'Moaning Myrtle', 'Voldemort'],
		locations: ["Diagon Alley", "Hogwartz", "Privet Drive", "The Ministry of Magic", "The Chamber of Secrets"],
		props: ['the snitch', "a horcrux", "the invisibility cloak", "the elder wand", "the Whomping Willow", "Nimbus 2000"],
		fuckingWat: false
	}),
	Ember.Object.create({
		name: "Teen Wolf",
		google: 9610000,
		popularity: 65,
		weirdness: 0.05,
		genre: ['fantasy', 'romance', 'drama', 'sci-fi'],
		medium: 'tv',
		characters: ['Derek', 'Scott', 'Styles', 'The Sheriff', 'Lydia', 'Chris Argent', 'Peter', 'Danny', 'Jackson', 'Malia'],
		locations: ["Derek's Loft", 'Beacon Hills', 'the vetrinary clinic', 'Mexico'],
		props: ['wolfsbane', "Derek's eyebrows", "mistletoe", 'mountain ash', 'a banshee'],
		fuckingWat: false
	}),
	Ember.Object.create({
		name: "Shrek",
		google: 12400000,
		popularity: 20,
		weirdness: 0.7,
		genre: ['comedy', 'kids', 'romance'],
		medium: 'movie',
		characters: ['Shrek', 'Fiona', 'Donkey', 'Lord Farquad', 'The Gingerbread Man', 'Fairy Godmother', 'The First blind Mouse'],
		locations: ["Shrek's Swamp", 'Far Far Away Land', 'a Giant Tower'],
		props: ['a magic potion', 'gumdrop buttons', "true love's kiss"],
		fuckingWat: true
	}),
	Ember.Object.create({
		name: 'Avatar the Last Airbender',
		google: 13500000,
		popularity: 45,
		weirdness: 0.1,
		genre: ['fantasy', 'drama'],
		medium: 'tv',
		characters: ['Aang', 'Katara', 'Sokka', 'Toph', 'Zuko', 'Uncle Iroh', 'Appa', 'Momo', 'Azula', 'The Cabbage Vendor'],
		locations: ['The North Pole', 'Ba Sing Se', 'Kyoshi Island', 'The Spirit World', 'Ember Island'],
		props: ['a boomerang', 'a water bending scroll', 'jasmine tea', 'cabbages'],
		fuckingWat: false
	}),
	Ember.Object.create({
		name: 'Daria',
		google: 15700000,
		popularity: 15,
		weirdness: 0.6,
		genre: ['drama', 'comedy'],
		medium: 'tv',
		characters: ['Daria', 'Jane', 'Trent', 'Quinn', 'Helen', 'Up-chuck', 'Jake', 'Kevin', 'Brittany', 'Jodie'],
		locations: ['Lawndale High', 'Cashmans', 'The Mall', 'Pizza King'],
		props: ['an issue of sick sad world', 'Ultra Cola', 'pizza', 'self esteem'],
		fuckingWat: true
	}),
	Ember.Object.create({
		name: 'Glee',
		google: 27900000,
		popularity: 50,
		weirdness: 0.05,
		genre: ['drama', 'comedy', 'romance'],
		medium: 'tv',
		characters: ['Finn', 'Rachel', 'Quinn', 'Santana', 'Sam', 'Brittany', 'Artie', 'Kurt', 'Mr. Schue', 'Sue Sylvester'],
		locations: ['The Choir Room', 'The Football Field', 'The Gym', 'Matress Land'],
		props: ['a slushie', "Artie's wheelchair", "Sue's Journal", 'a musical number'],
		fuckingWat: false
	}),
	Ember.Object.create({
		name: 'Sherlock',
		google: 24200000,
		popularity: 25,
		weirdness: 0.13,
		genre: ['drama', 'mystery'],
		medium: 'tv',
		characters: ['Sherlock Holmes', 'Dr. Watson', 'Jim Moriarty', 'Mycroft', 'Mrs. Hudson', 'Irene Adler'],
		locations: ['London', 'New Scotland Yard', '221B Baker Street', "Speedy's Cafe", "St. Bart's Hospital"],
		props: ['Deerstalker Hat', 'Mind Palace', 'intuition', "Watson's Blog", "a magnifying glass"],
		fuckingWat: false
	}),
	Ember.Object.create({
		name: 'Stargate: SG-1',
		google: 13100000,
		popularity: 25,
		weirdness: 0.17,
		genre: ['sci-fi'],
		medium: 'tv',
		characters: ["Jack O'Neill", "Teal'c", "Samantha Carter", "Daniel Jackson", "Dr. Janet Fraiser", "Apophis"],
		locations: ['Pegasus Galaxy', "Othala", "Goa'uld Pleasure Palace", "Abydos", "Cheyenne Mountain Complex", "the Stargate Control Room"],
		props: ['Naqahdah', 'Zero Point Module', "a Goa'uld symbiote", "a Sarcophagus", "another Stargate"],
		fuckingWat: false
	}),
	Ember.Object.create({
		"name": "Teenage Mutant Ninja Turtles",
		"google": 24000000,
		"popularity": 65,
		"weirdness": 0.08,
		"genre": ["action", "adventure"],
		"medium": "cartoon",
		"characters": ["Leonardo", "Michelangelo", "Raphael", "Donatello", "Splinter", "April O'Neil", "Casey Jones", "Shredder", "Karai", "Foot Soldier #6", "Krang", "Rocksteady", "Bebop", "Baxter Stockman", "Tokka", "Rahzar"],
		"locations": ["Manhattan", "Technodrome", "Dimension X", "The Foot Clan's secret lair"],
		"props": ["ooze", "pizza", "the sewer", "'cowabunga!'", "Splinter's training"],
		"fuckingWat": false
	}),
	Ember.Object.create({
		"name": "The Legend of Zelda",
		"google": 8300000,
		"popularity": 45,
		"weirdness": 0.3,
		"genre": ["action", "adventure", "drama"],
		"medium": "video game",
		"characters": ["Link", "Dark Link", "Princess Zelda", "Ganondorf", "Epona", "Sheik", "Zora", "Agahnim", "Lanayru, The Thunder Dragon"],
		"locations": ["Hyrule", "Temple of Time", "Ikana Canyon", "Dark World", "Sky Keep"],
		"props": ["an ocarina", "a deku nut", "Bomber's Notebook", "a Jar of Milk", "the Triforce", "the Master Sword"],
		"fuckingWat": false
	}),
	Ember.Object.create({
		name: 'Pokemon',
		google: 59500000,
		popularity: 40,
		weirdness: 0.4,
		genre: [''],
		medium: 'video game',
		characters: ['Ash', 'Misty', 'Brock', 'Pikachu', 'Jesse', 'James', 'Meowth', 'Professor Oak'],
		locations: ['Palette Town', 'Mt. Moon', 'Lavendar Town', 'Pewter City', 'Silph Co.'],
		props: ['a masterball', 'The Marsh Badge', 'a pokeflute', 'tickets to the S.S. Anne', 'Team Rocket Blasting off Again!']
	}),
	Ember.Object.create({
		name: "Game of Thrones",
		google: 46300000,
		popularity: 75,
		weirdness: 0.05,
		genre: ["fantasy", "adventure", "drama"],
		medium: "television",
		characters: [
			"Tyrion Lannister",
			"Cersei Lannister",
			"Daenerys Targaryen",
			"Jon Snow",
			"Brienne of Tarth",
			"Gendry",
			"Ygritte",
			"Stannis Baratheon",
			"Khal Drogo",
			"Daario Naharis",
			"Sansa Stark",
			"Shae",
			"Eddard Stark",
			"Tywin Lannister"
		],
		locations: [
			"King's Landing",
			"Casterly Rock",
			"The Wall",
			"Red Keep",
			"Qarth",
			"Castle Black",
			"Haunted Forest",
			"Slaver's Bay",
			"North of the Wall",
			"The North",
			"Iron Islands",
			"Flea Bottom"
		],
		props: [
			"Tywin's missing hand",
			"Eddard's missing head",
			"Milk of the Poppy",
			"the Iron Throne",
			"Wildfire",
			"Needle",
			"Oathkeeper"
		],
		fuckingWat: false
	}), Ember.Object.create({
		name: 'Dr. Quinn, Medicine Woman',
		google: 1000000,
		popularity: 10,
		weirdness: 0.96,
		genre: ['drama', 'western'],
		medium: 'tv',
		characters: ['Dr. Quinn, Medicine Woman', 'Byron Sully', 'Chief Black Kettle'],
		locations: ['Colorado Springs', "Grace's Cafe", "Gold Nugget Saloon and Hotel"],
		props: ["Doctor's Bag", "Typhus", "Influenza"],
		fuckingWat: true
	}), Ember.Object.create({
		name: 'Hamlet',
		google: 11800000,
		popularity: 30,
		weirdness: 0.90,
		genre: ['drama', 'tragedy'],
		medium: 'play',
		characters: ['Hamlet', 'Ophelia', "Rosencrantz and Guildenstern", "Fortinbras", "the Ghost of Hamlet's Father"],
		locations: ["Denmark", "Elsinore", "the Queen's Closet"],
		props: ["Yorick's skull", 'indecisiveness', "poison"],
		fuckingWat: true
	}), Ember.Object.create({
		name: 'The Lord of the Rings',
		google: 55000000,
		popularity: 70,
		weirdness: 0.43,
		genre: ['drama', 'fantasy'],
		medium: 'play',
		characters: ["Frodo Baggins", "Samwise Gamgee", "Gandalf the Grey", "Gandalf the White", "Smeagol", "Gollum", "Elrond", "Gimli", "Sauron", "Treebeard", "Tom Bombadil"],
		locations: ["Mt. Doom", "Mordor", "Bagend", "Rivendell", "Khazad-dum", "Barad-dûr", "The Black Gate", "The Shire"],
		props: ["The One Ring", "Anduril", "the Shards of Narsil", "palantir", "Ents", "Potatos, PO-TAY-TOES", 'Sting', "Mithril", "Horn of Helm Hammerhand"],
		fuckingWat: false
	}),



]);